# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0337950af29f9e4c78a74b57aa5c0665b75efe8a4b03df5ca65080c678877befe52b4eb9b703f8519d30a5e9748d6fb624d7ddb49f88970006090e05a62e7c69

test:
  secret_key_base: 004f8ad4decd2f30fe956940885dac2e82985bb8715aee98459407e6201e8723f160efbee05ad331bb95dba1350856a271d27eb99bf6df10a590f58555b5730b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
